import Head from 'next/head';

import { Drawer } from '../components/drawer/Drawer';
import { Timer } from '../components/timer/Timer';
import styles from '../styles/Home.module.css';

import { useState, useEffect } from 'react';

export default function Home() {
  const [bgColor, setBgColor] = useState('#8ED1FC');
  const [fontColor, setFontColor] = useState('#fff');
  const [waifu, setWaifu] = useState('/rem.png');
  const [flowType, setFlowType] = useState('pomo');
  const [workTime, setWorkTime] = useState(25 * 60);
  const [breakTime, setBreakTime] = useState(5 * 60);
  const [longBreakTime, setLongBreakTime] = useState(25 * 60);

  useEffect(() => {
    if (localStorage.getItem('waifu')) {
      setWaifu(localStorage.getItem('waifu'));
    }
    if (localStorage.getItem('bgColor')) {
      setBgColor(localStorage.getItem('bgColor'));
    }
    if (localStorage.getItem('fontColor')) {
      setFontColor(localStorage.getItem('fontColor'));
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} style={{ color: fontColor }}>
        <Drawer
          bgColor={bgColor}
          setBgColor={setBgColor}
          fontColor={fontColor}
          setFontColor={setFontColor}
          setWaifu={setWaifu}
          flowType={flowType}
          setFlowType={setFlowType}
          workTime={workTime}
          setWorkTime={setWorkTime}
          breakTime={breakTime}
          setBreakTime={setBreakTime}
          longBreakTime={longBreakTime}
          setLongBreakTime={setLongBreakTime}
        />
        <Timer
          bgColor={bgColor}
          waifu={waifu}
          flowType={flowType}
          setFlowType={setFlowType}
          workTime={workTime}
          breakTime={breakTime}
          longBreakTime={longBreakTime}
        />
      </main>
    </div>
  );
}
