import Head from 'next/head';
import Image from 'next/image';

import { Drawer } from '../components/drawer/drawer';
import { Timer } from '../components/timer/timer';
import styles from '../styles/Home.module.css';

import { useState } from 'react';

export default function Home() {
  const [bgColor, setBgColor] = useState('#1d1d1d');
  const [fontColor, setFontColor] = useState('#fff');
  const [waifu, setWaifu] = useState('/rem.png');
  const [flowType, setFlowType] = useState('pomo');

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} style={{ color: fontColor }}>
        <Drawer
          bgColor={bgColor}
          setBgColor={setBgColor}
          setFontColor={setFontColor}
          setWaifu={setWaifu}
          flowType={flowType}
          setFlowType={setFlowType}
        />
        <Timer bgColor={bgColor} waifu={waifu} flowType={flowType} setFlowType={setFlowType} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
